# Site settings
title: Adif Hermawan - Just Worker
description: A blog about lorem ipsum dolor sit amet.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adif Hermawan
user_description: Welcome to my world
user_title: Devloper Gabux
email: contact@adif.tech
twitter_username: adifher
github_username:  adif48
paypal_username:  adifher
instagram_username:  adifher
telegram_username:  adifher
year: 2018

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
